### ISSUE TITLE
菜单栏将 redis key 的 : 分隔符识别成了目录

### ISSUE THREAD

**Issue by why444216978** [gphper/grm#3]
想问一下这个是有意设计成这样的嘛？
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/29140252/183296974-b69ebf32-4ed6-476b-b76b-73684824fccb.png">

**Comment by gphper** [comment]
是的，默认分隔符是  :

**Comment by why444216978** [comment]
有很多业务场景下，是用冒号作为分隔符的，这里分目录的目的是什么呢，redis我理解key之间是打平的

**Comment by gphper** [comment]
单纯就是为了查看某一类key值的时候方便

**Comment by why444216978** [comment]
不过如果 : 很多，看一个 key 需要点很多次了，看某一类值，似乎用 keys 匹配更合理
