### ISSUE TITLE
key 过滤不好用

### ISSUE THREAD

**Issue by simake2017** [gphper/grm#5]
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/31234273/184056057-89a2b776-3935-46e6-8c67-6242dd1cbe56.png">

这里的匹配不好用呢 ，总是出不来

<img width="673" alt="image" src="https://user-images.githubusercontent.com/31234273/184056101-1effe582-0575-41aa-9d1b-f9338a930693.png">

再就是get的时候 一直卡主出不来，我的key 大概有2万多

**Comment by gphper** [comment]
过滤使用的 scan 命令，这个命令不能保证返回数据的个数所以执行完命令之后可能就返回一个值，需要点击下一页才能继续查找，这块好像确实不太方便，我想想怎么优化下，命令行的我这边没试出来问题，你看下是不是ws连接断开了

**Comment by simake2017** [comment]
好滴
